name: Test

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - ".github/workflows/test.yml"

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno-version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno-version }}"
      - uses: actions/cache@v3
        with:
          key: deno-${{ hashFiles('**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno-version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno-version }}"
      - uses: actions/cache@v3
        with:
          key: deno-${{ hashFiles('**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Cache
        run: deno task cache
      - name: Test
        run: deno task test
      - name: Coverage
        run: deno task coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
